trigger:
- release
- dev

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-22.04'
  steps:
  - script: |
      sudo apt-get -qq update;
      sudo pip install --upgrade pip
      sudo apt-get install python-setuptools;
      sudo apt-get install libglew-dev libxrandr-dev libxxf86vm-dev libxcursor-dev libxinerama-dev libxi-dev
      sudo python build_scripts/build_osd.py --tests --onetbb --omp --build $HOME/OSDgen/build --src $HOME/OSDgen/src $HOME/OSDinst
    displayName: 'Building OpenSubdiv'
  - script: |
      cd $HOME/OSDgen/build/s
      sudo ctest -T test -R "bfr|far"
    displayName: 'Testing OpenSubdiv'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: cTest
      testResultsFiles: /home/vsts/OSDgen/build/s/Testing/*/Test.xml
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'osd-linux'
      targetPath: "/home/vsts/OSDinst"


- job: macOS
  pool:
    vmImage: 'macOS-14'
  steps:
  - script: |
      /bin/bash -c "sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer"
      python build_scripts/build_osd.py --tests --onetbb --generator Xcode --build $HOME/OSDgen/build --src $HOME/OSDgen/src $HOME/OSDinst
    displayName: 'Building OpenSubdiv'
  - script: |
      cd $HOME/OSDgen/build/s
      ctest -T test -R "bfr|far"
    displayName: 'Testing OpenSubdiv'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: cTest
      testResultsFiles: /Users/runner/OSDgen/build/s/Testing/*/Test.xml
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'osd-macOS'
      targetPath: "/Users/runner/OSDinst"

- job: Windows
  pool:
    vmImage: 'windows-2022'
  steps:
  - script: |
      call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
      call python build_scripts/build_osd.py --tests --onetbb --omp --build %HOME%/OSDgen/build --src %HOME%/OSDgen/src %HOME%/OSDinst
    displayName: 'Building OpenSubdiv'
  - script: |
      cd %HOME%/OSDgen/build/s
      ctest -T test -R "bfr|far"
    displayName: 'Testing OpenSubdiv'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: cTest
      testResultsFiles: D:/OSDgen/build/s/Testing/*/Test.xml
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'osd-win64'
      targetPath: "D:/OSDinst"
